apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clickhouse
spec:
  selector:
    app: {{ .Release.Name }}-clickhouse
  type: {{ .Values.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePortHttp }}
      nodePort: {{ .Values.service.nodePortHttp }}
      {{- end }}
