apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
data:
  superset_config.py: |
    SECRET_KEY = "cmU+swUM0+UhQm3RDXGXtlqrpNINSQkucU2TFEbvoxUFumVYNHNGBv/m"
    ENABLE_PROXY_FIX = True

    AUTH_ROLE_PUBLIC = 'Gamma'
