apiVersion: v1
kind: Service
metadata:
  name: superset-postgresql
spec:
  ports:
    - port: 5432
  selector:
    app: superset-postgresql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: superset-postgresql
spec:
  selector:
    matchLabels:
      app: superset-postgresql
  serviceName: "superset-postgresql"
  replicas: 1
  template:
    metadata:
      labels:
        app: superset-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: superset
            - name: POSTGRES_USER
              value: superset
            - name: POSTGRES_PASSWORD
              value: superset
          volumeMounts:
            - name: postgres-pv
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-pv
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
