apiVersion: v1
kind: Service
metadata:
  name: superset
spec:
  type: {{ .Values.service.type }}
  selector:
    app: superset
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8088
      nodePort: {{ .Values.service.nodePort }}
